/**
 * MQL5's predefined enumerations and constants.
 *
 * Values that programs are known to compare or store (timeframes, order and
 * position types, trade actions and return codes, MA methods, applied prices,
 * init results) carry MetaTrader's real numbers. Property identifiers
 * (SYMBOL_BID, ACCOUNT_BALANCE, …) are only ever passed back into the
 * runtime, so they just need to be distinct within their enumeration.
 */

export type EnumTable = Record<string, [name: string, value: number][]>;

function seq(names: string[], start = 0): [string, number][] {
  return names.map((name, i) => [name, start + i]);
}

export const BUILTIN_ENUMS: EnumTable = {
  ENUM_TIMEFRAMES: [
    ['PERIOD_CURRENT', 0], ['PERIOD_M1', 1], ['PERIOD_M2', 2], ['PERIOD_M3', 3], ['PERIOD_M4', 4],
    ['PERIOD_M5', 5], ['PERIOD_M6', 6], ['PERIOD_M10', 10], ['PERIOD_M12', 12], ['PERIOD_M15', 15],
    ['PERIOD_M20', 20], ['PERIOD_M30', 30], ['PERIOD_H1', 16385], ['PERIOD_H2', 16386], ['PERIOD_H3', 16387],
    ['PERIOD_H4', 16388], ['PERIOD_H6', 16390], ['PERIOD_H8', 16392], ['PERIOD_H12', 16396],
    ['PERIOD_D1', 16408], ['PERIOD_W1', 32769], ['PERIOD_MN1', 49153],
  ],
  ENUM_MA_METHOD: seq(['MODE_SMA', 'MODE_EMA', 'MODE_SMMA', 'MODE_LWMA']),
  ENUM_APPLIED_PRICE: seq(['PRICE_CLOSE', 'PRICE_OPEN', 'PRICE_HIGH', 'PRICE_LOW', 'PRICE_MEDIAN', 'PRICE_TYPICAL', 'PRICE_WEIGHTED'], 1),
  ENUM_APPLIED_VOLUME: seq(['VOLUME_TICK', 'VOLUME_REAL']),
  ENUM_STO_PRICE: seq(['STO_LOWHIGH', 'STO_CLOSECLOSE']),
  ENUM_ORDER_TYPE: seq([
    'ORDER_TYPE_BUY', 'ORDER_TYPE_SELL', 'ORDER_TYPE_BUY_LIMIT', 'ORDER_TYPE_SELL_LIMIT', 'ORDER_TYPE_BUY_STOP',
    'ORDER_TYPE_SELL_STOP', 'ORDER_TYPE_BUY_STOP_LIMIT', 'ORDER_TYPE_SELL_STOP_LIMIT', 'ORDER_TYPE_CLOSE_BY',
  ]),
  ENUM_ORDER_TYPE_FILLING: seq(['ORDER_FILLING_FOK', 'ORDER_FILLING_IOC', 'ORDER_FILLING_RETURN', 'ORDER_FILLING_BOC']),
  ENUM_ORDER_TYPE_TIME: seq(['ORDER_TIME_GTC', 'ORDER_TIME_DAY', 'ORDER_TIME_SPECIFIED', 'ORDER_TIME_SPECIFIED_DAY']),
  ENUM_ORDER_STATE: seq([
    'ORDER_STATE_STARTED', 'ORDER_STATE_PLACED', 'ORDER_STATE_CANCELED', 'ORDER_STATE_PARTIAL', 'ORDER_STATE_FILLED',
    'ORDER_STATE_REJECTED', 'ORDER_STATE_EXPIRED', 'ORDER_STATE_REQUEST_ADD', 'ORDER_STATE_REQUEST_MODIFY',
    'ORDER_STATE_REQUEST_CANCEL',
  ]),
  ENUM_ORDER_REASON: seq(['ORDER_REASON_CLIENT', 'ORDER_REASON_MOBILE', 'ORDER_REASON_WEB', 'ORDER_REASON_EXPERT', 'ORDER_REASON_SL', 'ORDER_REASON_TP', 'ORDER_REASON_SO']),
  ENUM_POSITION_TYPE: seq(['POSITION_TYPE_BUY', 'POSITION_TYPE_SELL']),
  ENUM_POSITION_REASON: seq(['POSITION_REASON_CLIENT', 'POSITION_REASON_MOBILE', 'POSITION_REASON_WEB', 'POSITION_REASON_EXPERT']),
  ENUM_DEAL_TYPE: seq([
    'DEAL_TYPE_BUY', 'DEAL_TYPE_SELL', 'DEAL_TYPE_BALANCE', 'DEAL_TYPE_CREDIT', 'DEAL_TYPE_CHARGE', 'DEAL_TYPE_CORRECTION',
    'DEAL_TYPE_BONUS', 'DEAL_TYPE_COMMISSION', 'DEAL_TYPE_COMMISSION_DAILY', 'DEAL_TYPE_COMMISSION_MONTHLY',
    'DEAL_TYPE_COMMISSION_AGENT_DAILY', 'DEAL_TYPE_COMMISSION_AGENT_MONTHLY', 'DEAL_TYPE_INTEREST', 'DEAL_TYPE_BUY_CANCELED',
    'DEAL_TYPE_SELL_CANCELED', 'DEAL_DIVIDEND', 'DEAL_DIVIDEND_FRANKED', 'DEAL_TAX',
  ]),
  ENUM_DEAL_ENTRY: seq(['DEAL_ENTRY_IN', 'DEAL_ENTRY_OUT', 'DEAL_ENTRY_INOUT', 'DEAL_ENTRY_OUT_BY']),
  ENUM_DEAL_REASON: seq([
    'DEAL_REASON_CLIENT', 'DEAL_REASON_MOBILE', 'DEAL_REASON_WEB', 'DEAL_REASON_EXPERT', 'DEAL_REASON_SL', 'DEAL_REASON_TP',
    'DEAL_REASON_SO', 'DEAL_REASON_ROLLOVER', 'DEAL_REASON_VMARGIN', 'DEAL_REASON_SPLIT',
  ]),
  ENUM_TRADE_REQUEST_ACTIONS: [
    ['TRADE_ACTION_DEAL', 1], ['TRADE_ACTION_PENDING', 5], ['TRADE_ACTION_SLTP', 6], ['TRADE_ACTION_MODIFY', 7],
    ['TRADE_ACTION_REMOVE', 8], ['TRADE_ACTION_CLOSE_BY', 10],
  ],
  ENUM_TRADE_TRANSACTION_TYPE: seq([
    'TRADE_TRANSACTION_ORDER_ADD', 'TRADE_TRANSACTION_ORDER_UPDATE', 'TRADE_TRANSACTION_ORDER_DELETE',
    'TRADE_TRANSACTION_HISTORY_ADD', 'TRADE_TRANSACTION_HISTORY_UPDATE', 'TRADE_TRANSACTION_HISTORY_DELETE',
    'TRADE_TRANSACTION_DEAL_ADD', 'TRADE_TRANSACTION_DEAL_UPDATE', 'TRADE_TRANSACTION_DEAL_DELETE',
    'TRADE_TRANSACTION_POSITION', 'TRADE_TRANSACTION_REQUEST',
  ]),
  ENUM_SYMBOL_INFO_DOUBLE: seq([
    'SYMBOL_BID', 'SYMBOL_BIDHIGH', 'SYMBOL_BIDLOW', 'SYMBOL_ASK', 'SYMBOL_ASKHIGH', 'SYMBOL_ASKLOW', 'SYMBOL_LAST',
    'SYMBOL_LASTHIGH', 'SYMBOL_LASTLOW', 'SYMBOL_VOLUME_REAL', 'SYMBOL_VOLUMEHIGH_REAL', 'SYMBOL_VOLUMELOW_REAL',
    'SYMBOL_POINT', 'SYMBOL_TRADE_TICK_VALUE', 'SYMBOL_TRADE_TICK_VALUE_PROFIT', 'SYMBOL_TRADE_TICK_VALUE_LOSS',
    'SYMBOL_TRADE_TICK_SIZE', 'SYMBOL_TRADE_CONTRACT_SIZE', 'SYMBOL_TRADE_ACCRUED_INTEREST', 'SYMBOL_TRADE_FACE_VALUE',
    'SYMBOL_TRADE_LIQUIDITY_RATE', 'SYMBOL_VOLUME_MIN', 'SYMBOL_VOLUME_MAX', 'SYMBOL_VOLUME_STEP', 'SYMBOL_VOLUME_LIMIT',
    'SYMBOL_SWAP_LONG', 'SYMBOL_SWAP_SHORT', 'SYMBOL_MARGIN_INITIAL', 'SYMBOL_MARGIN_MAINTENANCE',
    'SYMBOL_SESSION_VOLUME', 'SYMBOL_SESSION_TURNOVER', 'SYMBOL_SESSION_INTEREST', 'SYMBOL_SESSION_BUY_ORDERS_VOLUME',
    'SYMBOL_SESSION_SELL_ORDERS_VOLUME', 'SYMBOL_SESSION_OPEN', 'SYMBOL_SESSION_CLOSE', 'SYMBOL_SESSION_AW',
    'SYMBOL_SESSION_PRICE_SETTLEMENT', 'SYMBOL_SESSION_PRICE_LIMIT_MIN', 'SYMBOL_SESSION_PRICE_LIMIT_MAX',
    'SYMBOL_MARGIN_HEDGED', 'SYMBOL_PRICE_CHANGE', 'SYMBOL_PRICE_VOLATILITY', 'SYMBOL_PRICE_THEORETICAL',
    'SYMBOL_SWAP_SUNDAY', 'SYMBOL_SWAP_MONDAY', 'SYMBOL_SWAP_TUESDAY', 'SYMBOL_SWAP_WEDNESDAY', 'SYMBOL_SWAP_THURSDAY',
    'SYMBOL_SWAP_FRIDAY', 'SYMBOL_SWAP_SATURDAY',
  ]),
  ENUM_SYMBOL_INFO_INTEGER: seq([
    'SYMBOL_SELECT', 'SYMBOL_VISIBLE', 'SYMBOL_SESSION_DEALS', 'SYMBOL_SESSION_BUY_ORDERS', 'SYMBOL_SESSION_SELL_ORDERS',
    'SYMBOL_VOLUME', 'SYMBOL_VOLUMEHIGH', 'SYMBOL_VOLUMELOW', 'SYMBOL_TIME', 'SYMBOL_TIME_MSC', 'SYMBOL_DIGITS',
    'SYMBOL_SPREAD_FLOAT', 'SYMBOL_SPREAD', 'SYMBOL_TICKS_BOOKDEPTH', 'SYMBOL_TRADE_CALC_MODE', 'SYMBOL_TRADE_MODE',
    'SYMBOL_START_TIME', 'SYMBOL_EXPIRATION_TIME', 'SYMBOL_TRADE_STOPS_LEVEL', 'SYMBOL_TRADE_FREEZE_LEVEL',
    'SYMBOL_TRADE_EXEMODE', 'SYMBOL_SWAP_MODE', 'SYMBOL_SWAP_ROLLOVER3DAYS', 'SYMBOL_MARGIN_HEDGED_USE_LEG',
    'SYMBOL_EXPIRATION_MODE', 'SYMBOL_FILLING_MODE', 'SYMBOL_ORDER_MODE', 'SYMBOL_ORDER_GTC_MODE', 'SYMBOL_OPTION_MODE',
    'SYMBOL_OPTION_RIGHT', 'SYMBOL_EXIST', 'SYMBOL_CUSTOM', 'SYMBOL_BACKGROUND_COLOR', 'SYMBOL_CHART_MODE',
    'SYMBOL_MARGIN_HEDGED_USE_LEG_', 'SYMBOL_INDUSTRY', 'SYMBOL_SECTOR',
  ]),
  ENUM_SYMBOL_INFO_STRING: seq([
    'SYMBOL_BASIS', 'SYMBOL_CATEGORY', 'SYMBOL_COUNTRY', 'SYMBOL_SECTOR_NAME', 'SYMBOL_INDUSTRY_NAME',
    'SYMBOL_CURRENCY_BASE', 'SYMBOL_CURRENCY_PROFIT', 'SYMBOL_CURRENCY_MARGIN', 'SYMBOL_BANK', 'SYMBOL_DESCRIPTION',
    'SYMBOL_EXCHANGE', 'SYMBOL_FORMULA', 'SYMBOL_ISIN', 'SYMBOL_NAME', 'SYMBOL_PAGE', 'SYMBOL_PATH',
  ]),
  ENUM_SYMBOL_TRADE_MODE: seq([
    'SYMBOL_TRADE_MODE_DISABLED', 'SYMBOL_TRADE_MODE_LONGONLY', 'SYMBOL_TRADE_MODE_SHORTONLY',
    'SYMBOL_TRADE_MODE_CLOSEONLY', 'SYMBOL_TRADE_MODE_FULL',
  ]),
  ENUM_SYMBOL_TRADE_EXECUTION: seq([
    'SYMBOL_TRADE_EXECUTION_REQUEST', 'SYMBOL_TRADE_EXECUTION_INSTANT', 'SYMBOL_TRADE_EXECUTION_MARKET',
    'SYMBOL_TRADE_EXECUTION_EXCHANGE',
  ]),
  ENUM_SYMBOL_CALC_MODE: [
    ['SYMBOL_CALC_MODE_FOREX', 0], ['SYMBOL_CALC_MODE_FUTURES', 1], ['SYMBOL_CALC_MODE_CFD', 2],
    ['SYMBOL_CALC_MODE_CFDINDEX', 3], ['SYMBOL_CALC_MODE_CFDLEVERAGE', 4], ['SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE', 5],
    ['SYMBOL_CALC_MODE_EXCH_STOCKS', 32], ['SYMBOL_CALC_MODE_EXCH_FUTURES', 33], ['SYMBOL_CALC_MODE_SERV_COLLATERAL', 64],
  ],
  ENUM_SYMBOL_SWAP_MODE: seq([
    'SYMBOL_SWAP_MODE_DISABLED', 'SYMBOL_SWAP_MODE_POINTS', 'SYMBOL_SWAP_MODE_CURRENCY_SYMBOL',
    'SYMBOL_SWAP_MODE_CURRENCY_MARGIN', 'SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT', 'SYMBOL_SWAP_MODE_INTEREST_CURRENT',
    'SYMBOL_SWAP_MODE_INTEREST_OPEN', 'SYMBOL_SWAP_MODE_REOPEN_CURRENT', 'SYMBOL_SWAP_MODE_REOPEN_BID',
  ]),
  ENUM_ACCOUNT_INFO_DOUBLE: seq([
    'ACCOUNT_BALANCE', 'ACCOUNT_CREDIT', 'ACCOUNT_PROFIT', 'ACCOUNT_EQUITY', 'ACCOUNT_MARGIN', 'ACCOUNT_MARGIN_FREE',
    'ACCOUNT_MARGIN_LEVEL', 'ACCOUNT_MARGIN_SO_CALL', 'ACCOUNT_MARGIN_SO_SO', 'ACCOUNT_MARGIN_INITIAL',
    'ACCOUNT_MARGIN_MAINTENANCE', 'ACCOUNT_ASSETS', 'ACCOUNT_LIABILITIES', 'ACCOUNT_COMMISSION_BLOCKED',
  ]),
  ENUM_ACCOUNT_INFO_INTEGER: seq([
    'ACCOUNT_LOGIN', 'ACCOUNT_TRADE_MODE', 'ACCOUNT_LEVERAGE', 'ACCOUNT_LIMIT_ORDERS', 'ACCOUNT_MARGIN_SO_MODE',
    'ACCOUNT_TRADE_ALLOWED', 'ACCOUNT_TRADE_EXPERT', 'ACCOUNT_MARGIN_MODE', 'ACCOUNT_CURRENCY_DIGITS', 'ACCOUNT_FIFO_CLOSE',
    'ACCOUNT_HEDGE_ALLOWED',
  ]),
  ENUM_ACCOUNT_INFO_STRING: seq(['ACCOUNT_NAME', 'ACCOUNT_SERVER', 'ACCOUNT_CURRENCY', 'ACCOUNT_COMPANY']),
  ENUM_ACCOUNT_TRADE_MODE: seq(['ACCOUNT_TRADE_MODE_DEMO', 'ACCOUNT_TRADE_MODE_CONTEST', 'ACCOUNT_TRADE_MODE_REAL']),
  ENUM_ACCOUNT_MARGIN_MODE: seq([
    'ACCOUNT_MARGIN_MODE_RETAIL_NETTING', 'ACCOUNT_MARGIN_MODE_EXCHANGE', 'ACCOUNT_MARGIN_MODE_RETAIL_HEDGING',
  ]),
  ENUM_ACCOUNT_STOPOUT_MODE: seq(['ACCOUNT_STOPOUT_MODE_PERCENT', 'ACCOUNT_STOPOUT_MODE_MONEY']),
  ENUM_POSITION_PROPERTY_DOUBLE: seq([
    'POSITION_VOLUME', 'POSITION_PRICE_OPEN', 'POSITION_SL', 'POSITION_TP', 'POSITION_PRICE_CURRENT', 'POSITION_SWAP',
    'POSITION_PROFIT', 'POSITION_COMMISSION',
  ]),
  ENUM_POSITION_PROPERTY_INTEGER: seq([
    'POSITION_TICKET', 'POSITION_TIME', 'POSITION_TIME_MSC', 'POSITION_TIME_UPDATE', 'POSITION_TIME_UPDATE_MSC',
    'POSITION_TYPE', 'POSITION_MAGIC', 'POSITION_IDENTIFIER', 'POSITION_REASON',
  ]),
  ENUM_POSITION_PROPERTY_STRING: seq(['POSITION_SYMBOL', 'POSITION_COMMENT', 'POSITION_EXTERNAL_ID']),
  ENUM_ORDER_PROPERTY_DOUBLE: seq([
    'ORDER_VOLUME_INITIAL', 'ORDER_VOLUME_CURRENT', 'ORDER_PRICE_OPEN', 'ORDER_SL', 'ORDER_TP', 'ORDER_PRICE_CURRENT',
    'ORDER_PRICE_STOPLIMIT',
  ]),
  ENUM_ORDER_PROPERTY_INTEGER: seq([
    'ORDER_TICKET', 'ORDER_TIME_SETUP', 'ORDER_TYPE', 'ORDER_STATE', 'ORDER_TIME_EXPIRATION', 'ORDER_TIME_DONE',
    'ORDER_TIME_SETUP_MSC', 'ORDER_TIME_DONE_MSC', 'ORDER_TYPE_FILLING', 'ORDER_TYPE_TIME', 'ORDER_MAGIC', 'ORDER_REASON',
    'ORDER_POSITION_ID', 'ORDER_POSITION_BY_ID',
  ]),
  ENUM_ORDER_PROPERTY_STRING: seq(['ORDER_SYMBOL', 'ORDER_COMMENT', 'ORDER_EXTERNAL_ID']),
  ENUM_DEAL_PROPERTY_DOUBLE: seq([
    'DEAL_VOLUME', 'DEAL_PRICE', 'DEAL_COMMISSION', 'DEAL_SWAP', 'DEAL_PROFIT', 'DEAL_FEE', 'DEAL_SL', 'DEAL_TP',
  ]),
  ENUM_DEAL_PROPERTY_INTEGER: seq([
    'DEAL_TICKET', 'DEAL_ORDER', 'DEAL_TIME', 'DEAL_TIME_MSC', 'DEAL_TYPE', 'DEAL_ENTRY', 'DEAL_MAGIC', 'DEAL_REASON',
    'DEAL_POSITION_ID',
  ]),
  ENUM_DEAL_PROPERTY_STRING: seq(['DEAL_SYMBOL', 'DEAL_COMMENT', 'DEAL_EXTERNAL_ID']),
  ENUM_TERMINAL_INFO_INTEGER: seq([
    'TERMINAL_BUILD', 'TERMINAL_COMMUNITY_ACCOUNT', 'TERMINAL_COMMUNITY_CONNECTION', 'TERMINAL_CONNECTED',
    'TERMINAL_DLLS_ALLOWED', 'TERMINAL_TRADE_ALLOWED', 'TERMINAL_EMAIL_ENABLED', 'TERMINAL_FTP_ENABLED',
    'TERMINAL_NOTIFICATIONS_ENABLED', 'TERMINAL_MAXBARS', 'TERMINAL_MQID', 'TERMINAL_CODEPAGE', 'TERMINAL_CPU_CORES',
    'TERMINAL_DISK_SPACE', 'TERMINAL_MEMORY_PHYSICAL', 'TERMINAL_MEMORY_TOTAL', 'TERMINAL_MEMORY_AVAILABLE',
    'TERMINAL_MEMORY_USED', 'TERMINAL_X64', 'TERMINAL_OPENCL_SUPPORT', 'TERMINAL_SCREEN_DPI', 'TERMINAL_SCREEN_LEFT',
    'TERMINAL_SCREEN_TOP', 'TERMINAL_SCREEN_WIDTH', 'TERMINAL_SCREEN_HEIGHT', 'TERMINAL_LEFT', 'TERMINAL_TOP',
    'TERMINAL_RIGHT', 'TERMINAL_BOTTOM', 'TERMINAL_PING_LAST', 'TERMINAL_VPS', 'TERMINAL_KEYSTATE_LEFT',
  ]),
  ENUM_TERMINAL_INFO_DOUBLE: seq(['TERMINAL_COMMUNITY_BALANCE', 'TERMINAL_RETRANSMISSION']),
  ENUM_TERMINAL_INFO_STRING: seq([
    'TERMINAL_LANGUAGE', 'TERMINAL_COMPANY', 'TERMINAL_NAME', 'TERMINAL_PATH', 'TERMINAL_DATA_PATH',
    'TERMINAL_COMMONDATA_PATH',
  ]),
  ENUM_MQL_INFO_INTEGER: seq([
    'MQL_PROGRAM_TYPE', 'MQL_DLLS_ALLOWED', 'MQL_TRADE_ALLOWED', 'MQL_SIGNALS_ALLOWED', 'MQL_DEBUG', 'MQL_PROFILER',
    'MQL_TESTER', 'MQL_FORWARD', 'MQL_OPTIMIZATION', 'MQL_VISUAL_MODE', 'MQL_FRAME_MODE', 'MQL_LICENSE_TYPE',
    'MQL_MEMORY_LIMIT', 'MQL_MEMORY_USED', 'MQL_HANDLES_USED',
  ]),
  ENUM_MQL_INFO_STRING: seq(['MQL_PROGRAM_NAME', 'MQL_PROGRAM_PATH']),
  ENUM_PROGRAM_TYPE: [['PROGRAM_SCRIPT', 1], ['PROGRAM_EXPERT', 2], ['PROGRAM_INDICATOR', 3], ['PROGRAM_SERVICE', 4]],
  ENUM_SERIES_INFO_INTEGER: seq([
    'SERIES_BARS_COUNT', 'SERIES_FIRSTDATE', 'SERIES_LASTBAR_DATE', 'SERIES_SERVER_FIRSTDATE', 'SERIES_TERMINAL_FIRSTDATE',
    'SERIES_SYNCHRONIZED',
  ]),
  ENUM_POINTER_TYPE: seq(['POINTER_INVALID', 'POINTER_DYNAMIC', 'POINTER_AUTOMATIC']),
  ENUM_INIT_RETCODE: seq(['INIT_SUCCEEDED', 'INIT_FAILED', 'INIT_PARAMETERS_INCORRECT', 'INIT_AGENT_NOT_SUITABLE']),
  ENUM_DAY_OF_WEEK: seq(['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY']),
  ENUM_OBJECT: [
    ['OBJ_VLINE', 0], ['OBJ_HLINE', 1], ['OBJ_TREND', 2], ['OBJ_TRENDBYANGLE', 3], ['OBJ_CYCLES', 4],
    ['OBJ_ARROWED_LINE', 108], ['OBJ_CHANNEL', 5], ['OBJ_STDDEVCHANNEL', 6], ['OBJ_REGRESSION', 7], ['OBJ_PITCHFORK', 8],
    ['OBJ_GANNLINE', 9], ['OBJ_GANNFAN', 10], ['OBJ_GANNGRID', 11], ['OBJ_FIBO', 12], ['OBJ_FIBOTIMES', 13],
    ['OBJ_FIBOFAN', 14], ['OBJ_FIBOARC', 15], ['OBJ_FIBOCHANNEL', 16], ['OBJ_EXPANSION', 17], ['OBJ_ELLIOTWAVE5', 18],
    ['OBJ_ELLIOTWAVE3', 19], ['OBJ_RECTANGLE', 20], ['OBJ_TRIANGLE', 21], ['OBJ_ELLIPSE', 22], ['OBJ_ARROW_THUMB_UP', 23],
    ['OBJ_ARROW_THUMB_DOWN', 24], ['OBJ_ARROW_UP', 25], ['OBJ_ARROW_DOWN', 26], ['OBJ_ARROW_STOP', 27],
    ['OBJ_ARROW_CHECK', 28], ['OBJ_ARROW_LEFT_PRICE', 29], ['OBJ_ARROW_RIGHT_PRICE', 30], ['OBJ_ARROW_BUY', 31],
    ['OBJ_ARROW_SELL', 32], ['OBJ_ARROW', 100], ['OBJ_TEXT', 101], ['OBJ_LABEL', 102], ['OBJ_BUTTON', 103],
    ['OBJ_CHART', 104], ['OBJ_BITMAP', 105], ['OBJ_BITMAP_LABEL', 106], ['OBJ_EDIT', 107], ['OBJ_EVENT', 109],
    ['OBJ_RECTANGLE_LABEL', 110],
  ],
  ENUM_OBJECT_PROPERTY_INTEGER: seq([
    'OBJPROP_COLOR', 'OBJPROP_STYLE', 'OBJPROP_WIDTH', 'OBJPROP_BACK', 'OBJPROP_ZORDER', 'OBJPROP_FILL', 'OBJPROP_HIDDEN',
    'OBJPROP_SELECTED', 'OBJPROP_READONLY', 'OBJPROP_TYPE', 'OBJPROP_TIME', 'OBJPROP_SELECTABLE', 'OBJPROP_CREATETIME',
    'OBJPROP_LEVELS', 'OBJPROP_LEVELCOLOR', 'OBJPROP_LEVELSTYLE', 'OBJPROP_LEVELWIDTH', 'OBJPROP_ALIGN', 'OBJPROP_FONTSIZE',
    'OBJPROP_RAY_LEFT', 'OBJPROP_RAY_RIGHT', 'OBJPROP_RAY', 'OBJPROP_ELLIPSE', 'OBJPROP_ARROWCODE', 'OBJPROP_TIMEFRAMES',
    'OBJPROP_ANCHOR', 'OBJPROP_XDISTANCE', 'OBJPROP_YDISTANCE', 'OBJPROP_DIRECTION', 'OBJPROP_DEGREE',
    'OBJPROP_DRAWLINES', 'OBJPROP_STATE', 'OBJPROP_CHART_ID', 'OBJPROP_XSIZE', 'OBJPROP_YSIZE', 'OBJPROP_XOFFSET',
    'OBJPROP_YOFFSET', 'OBJPROP_PERIOD', 'OBJPROP_DATE_SCALE', 'OBJPROP_PRICE_SCALE', 'OBJPROP_CHART_SCALE',
    'OBJPROP_BGCOLOR', 'OBJPROP_CORNER', 'OBJPROP_BORDER_TYPE', 'OBJPROP_BORDER_COLOR',
  ]),
  ENUM_OBJECT_PROPERTY_DOUBLE: seq(['OBJPROP_PRICE', 'OBJPROP_LEVELVALUE', 'OBJPROP_SCALE', 'OBJPROP_ANGLE', 'OBJPROP_DEVIATION']),
  ENUM_OBJECT_PROPERTY_STRING: seq([
    'OBJPROP_NAME', 'OBJPROP_TEXT', 'OBJPROP_TOOLTIP', 'OBJPROP_LEVELTEXT', 'OBJPROP_FONT', 'OBJPROP_BMPFILE',
    'OBJPROP_SYMBOL',
  ]),
  ENUM_BASE_CORNER: seq(['CORNER_LEFT_UPPER', 'CORNER_LEFT_LOWER', 'CORNER_RIGHT_LOWER', 'CORNER_RIGHT_UPPER']),
  ENUM_ANCHOR_POINT: seq([
    'ANCHOR_LEFT_UPPER', 'ANCHOR_LEFT', 'ANCHOR_LEFT_LOWER', 'ANCHOR_LOWER', 'ANCHOR_RIGHT_LOWER', 'ANCHOR_RIGHT',
    'ANCHOR_RIGHT_UPPER', 'ANCHOR_UPPER', 'ANCHOR_CENTER', 'ANCHOR_TOP', 'ANCHOR_BOTTOM',
  ]),
  ENUM_ALIGN_MODE: seq(['ALIGN_LEFT', 'ALIGN_CENTER', 'ALIGN_RIGHT']),
  ENUM_BORDER_TYPE: seq(['BORDER_FLAT', 'BORDER_RAISED', 'BORDER_SUNKEN']),
  ENUM_LINE_STYLE: seq(['STYLE_SOLID', 'STYLE_DASH', 'STYLE_DOT', 'STYLE_DASHDOT', 'STYLE_DASHDOTDOT']),
  ENUM_CHART_PROPERTY_INTEGER: seq([
    'CHART_SHOW', 'CHART_IS_OBJECT', 'CHART_BRING_TO_TOP', 'CHART_CONTEXT_MENU', 'CHART_CROSSHAIR_TOOL',
    'CHART_MOUSE_SCROLL', 'CHART_EVENT_MOUSE_WHEEL', 'CHART_EVENT_MOUSE_MOVE', 'CHART_EVENT_OBJECT_CREATE',
    'CHART_EVENT_OBJECT_DELETE', 'CHART_MODE', 'CHART_FOREGROUND', 'CHART_SHIFT', 'CHART_AUTOSCROLL', 'CHART_KEYBOARD_CONTROL',
    'CHART_QUICK_NAVIGATION', 'CHART_SCALE', 'CHART_SCALEFIX', 'CHART_SCALEFIX_11', 'CHART_SCALE_PT_PER_BAR',
    'CHART_SHOW_TICKER', 'CHART_SHOW_OHLC', 'CHART_SHOW_BID_LINE', 'CHART_SHOW_ASK_LINE', 'CHART_SHOW_LAST_LINE',
    'CHART_SHOW_PERIOD_SEP', 'CHART_SHOW_GRID', 'CHART_SHOW_VOLUMES', 'CHART_SHOW_OBJECT_DESCR', 'CHART_VISIBLE_BARS',
    'CHART_WINDOWS_TOTAL', 'CHART_WINDOW_IS_VISIBLE', 'CHART_WINDOW_HANDLE', 'CHART_WINDOW_YDISTANCE', 'CHART_FIRST_VISIBLE_BAR',
    'CHART_WIDTH_IN_BARS', 'CHART_WIDTH_IN_PIXELS', 'CHART_HEIGHT_IN_PIXELS', 'CHART_COLOR_BACKGROUND',
    'CHART_COLOR_FOREGROUND', 'CHART_COLOR_GRID', 'CHART_COLOR_VOLUME', 'CHART_COLOR_CHART_UP', 'CHART_COLOR_CHART_DOWN',
    'CHART_COLOR_CHART_LINE', 'CHART_COLOR_CANDLE_BULL', 'CHART_COLOR_CANDLE_BEAR', 'CHART_COLOR_BID', 'CHART_COLOR_ASK',
    'CHART_COLOR_LAST', 'CHART_COLOR_STOP_LEVEL', 'CHART_SHOW_TRADE_LEVELS', 'CHART_DRAG_TRADE_LEVELS',
    'CHART_SHOW_DATE_SCALE', 'CHART_SHOW_PRICE_SCALE', 'CHART_SHOW_ONE_CLICK', 'CHART_IS_MAXIMIZED', 'CHART_IS_MINIMIZED',
    'CHART_IS_DOCKED', 'CHART_FLOAT_LEFT', 'CHART_FLOAT_TOP', 'CHART_FLOAT_RIGHT', 'CHART_FLOAT_BOTTOM',
  ]),
  ENUM_CHART_PROPERTY_DOUBLE: seq(['CHART_SHIFT_SIZE', 'CHART_FIXED_POSITION', 'CHART_FIXED_MAX', 'CHART_FIXED_MIN', 'CHART_POINTS_PER_BAR', 'CHART_PRICE_MIN', 'CHART_PRICE_MAX']),
  ENUM_CHART_PROPERTY_STRING: seq(['CHART_COMMENT', 'CHART_EXPERT_NAME', 'CHART_SCRIPT_NAME']),
  ENUM_CHART_EVENT: seq([
    'CHARTEVENT_KEYDOWN', 'CHARTEVENT_MOUSE_MOVE', 'CHARTEVENT_OBJECT_CREATE', 'CHARTEVENT_OBJECT_CHANGE',
    'CHARTEVENT_OBJECT_DELETE', 'CHARTEVENT_CLICK', 'CHARTEVENT_OBJECT_CLICK', 'CHARTEVENT_OBJECT_DRAG',
    'CHARTEVENT_OBJECT_ENDEDIT', 'CHARTEVENT_CHART_CHANGE', 'CHARTEVENT_MOUSE_WHEEL',
  ]),
  ENUM_TRADE_RETCODE: [
    ['TRADE_RETCODE_REQUOTE', 10004], ['TRADE_RETCODE_REJECT', 10006], ['TRADE_RETCODE_CANCEL', 10007],
    ['TRADE_RETCODE_PLACED', 10008], ['TRADE_RETCODE_DONE', 10009], ['TRADE_RETCODE_DONE_PARTIAL', 10010],
    ['TRADE_RETCODE_ERROR', 10011], ['TRADE_RETCODE_TIMEOUT', 10012], ['TRADE_RETCODE_INVALID', 10013],
    ['TRADE_RETCODE_INVALID_VOLUME', 10014], ['TRADE_RETCODE_INVALID_PRICE', 10015], ['TRADE_RETCODE_INVALID_STOPS', 10016],
    ['TRADE_RETCODE_TRADE_DISABLED', 10017], ['TRADE_RETCODE_MARKET_CLOSED', 10018], ['TRADE_RETCODE_NO_MONEY', 10019],
    ['TRADE_RETCODE_PRICE_CHANGED', 10020], ['TRADE_RETCODE_PRICE_OFF', 10021], ['TRADE_RETCODE_INVALID_EXPIRATION', 10022],
    ['TRADE_RETCODE_ORDER_CHANGED', 10023], ['TRADE_RETCODE_TOO_MANY_REQUESTS', 10024], ['TRADE_RETCODE_NO_CHANGES', 10025],
    ['TRADE_RETCODE_SERVER_DISABLES_AT', 10026], ['TRADE_RETCODE_CLIENT_DISABLES_AT', 10027], ['TRADE_RETCODE_LOCKED', 10028],
    ['TRADE_RETCODE_FROZEN', 10029], ['TRADE_RETCODE_INVALID_FILL', 10030], ['TRADE_RETCODE_CONNECTION', 10031],
    ['TRADE_RETCODE_ONLY_REAL', 10032], ['TRADE_RETCODE_LIMIT_ORDERS', 10033], ['TRADE_RETCODE_LIMIT_VOLUME', 10034],
    ['TRADE_RETCODE_INVALID_ORDER', 10035], ['TRADE_RETCODE_POSITION_CLOSED', 10036],
    ['TRADE_RETCODE_INVALID_CLOSE_VOLUME', 10038], ['TRADE_RETCODE_CLOSE_ORDER_EXIST', 10039],
    ['TRADE_RETCODE_LIMIT_POSITIONS', 10040], ['TRADE_RETCODE_REJECT_CANCEL', 10041], ['TRADE_RETCODE_LONG_ONLY', 10042],
    ['TRADE_RETCODE_SHORT_ONLY', 10043], ['TRADE_RETCODE_CLOSE_ONLY', 10044], ['TRADE_RETCODE_FIFO_CLOSE', 10045],
  ],
  ENUM_DEINIT_REASON: seq([
    'REASON_PROGRAM', 'REASON_REMOVE', 'REASON_RECOMPILE', 'REASON_CHARTCHANGE', 'REASON_CHARTCLOSE', 'REASON_PARAMETERS',
    'REASON_ACCOUNT', 'REASON_TEMPLATE', 'REASON_INITFAILED', 'REASON_CLOSE',
  ]),
  ENUM_BOOK_TYPE: seq(['BOOK_TYPE_SELL', 'BOOK_TYPE_BUY', 'BOOK_TYPE_SELL_MARKET', 'BOOK_TYPE_BUY_MARKET'], 1),
  ENUM_FILE_POSITION: seq(['SEEK_SET', 'SEEK_CUR', 'SEEK_END']),
  ENUM_DATATYPE: seq(['TYPE_BOOL', 'TYPE_CHAR', 'TYPE_UCHAR', 'TYPE_SHORT', 'TYPE_USHORT', 'TYPE_COLOR', 'TYPE_INT', 'TYPE_UINT', 'TYPE_DATETIME', 'TYPE_LONG', 'TYPE_ULONG', 'TYPE_FLOAT', 'TYPE_DOUBLE', 'TYPE_STRING']),
  ENUM_INDICATOR: seq([
    'IND_AC', 'IND_AD', 'IND_ADX', 'IND_ADXW', 'IND_ALLIGATOR', 'IND_AMA', 'IND_AO', 'IND_ATR', 'IND_BANDS', 'IND_BEARS',
    'IND_BULLS', 'IND_BWMFI', 'IND_CCI', 'IND_CHAIKIN', 'IND_CUSTOM', 'IND_DEMA', 'IND_DEMARKER', 'IND_ENVELOPES',
    'IND_FORCE', 'IND_FRACTALS', 'IND_FRAMA', 'IND_GATOR', 'IND_ICHIMOKU', 'IND_MA', 'IND_MACD', 'IND_MFI',
    'IND_MOMENTUM', 'IND_OBV', 'IND_OSMA', 'IND_RSI', 'IND_RVI', 'IND_SAR', 'IND_STDDEV', 'IND_STOCHASTIC', 'IND_TEMA',
    'IND_TRIX', 'IND_VIDYA', 'IND_VOLUMES', 'IND_WPR',
  ]),
  ENUM_ORDER_FILLING_FLAGS: [['SYMBOL_FILLING_FOK', 1], ['SYMBOL_FILLING_IOC', 2], ['SYMBOL_FILLING_BOC', 4]],
  ENUM_SYMBOL_ORDER_GTC_MODE: seq(['SYMBOL_ORDERS_GTC', 'SYMBOL_ORDERS_DAILY', 'SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS']),
  ENUM_SYMBOL_CHART_MODE: seq(['SYMBOL_CHART_MODE_BID', 'SYMBOL_CHART_MODE_LAST']),
  ENUM_SERIESMODE: seq(['MODE_OPEN', 'MODE_LOW', 'MODE_HIGH', 'MODE_CLOSE', 'MODE_VOLUME', 'MODE_REAL_VOLUME', 'MODE_SPREAD']),
  // Strategy Tester statistics, read in OnTester; a live EA never gets there.
  ENUM_STATISTICS: seq([
    'STAT_INITIAL_DEPOSIT', 'STAT_WITHDRAWAL', 'STAT_PROFIT', 'STAT_GROSS_PROFIT', 'STAT_GROSS_LOSS',
    'STAT_MAX_PROFITTRADE', 'STAT_MAX_LOSSTRADE', 'STAT_CONPROFITMAX', 'STAT_CONPROFITMAX_TRADES',
    'STAT_MAX_CONWINS', 'STAT_MAX_CONPROFIT_TRADES', 'STAT_CONLOSSMAX', 'STAT_CONLOSSMAX_TRADES',
    'STAT_MAX_CONLOSSES', 'STAT_MAX_CONLOSS_TRADES', 'STAT_BALANCEMIN', 'STAT_BALANCE_DD',
    'STAT_BALANCEDD_PERCENT', 'STAT_BALANCE_DDREL_PERCENT', 'STAT_BALANCE_DD_RELATIVE', 'STAT_EQUITYMIN',
    'STAT_EQUITY_DD', 'STAT_EQUITYDD_PERCENT', 'STAT_EQUITY_DDREL_PERCENT', 'STAT_EQUITY_DD_RELATIVE',
    'STAT_EXPECTED_PAYOFF', 'STAT_PROFIT_FACTOR', 'STAT_RECOVERY_FACTOR', 'STAT_SHARPE_RATIO',
    'STAT_MIN_MARGINLEVEL', 'STAT_CUSTOM_ONTESTER', 'STAT_DEALS', 'STAT_TRADES', 'STAT_PROFIT_TRADES',
    'STAT_LOSS_TRADES', 'STAT_SHORT_TRADES', 'STAT_LONG_TRADES', 'STAT_PROFIT_SHORTTRADES',
    'STAT_PROFIT_LONGTRADES', 'STAT_PROFITTRADES_AVGCON', 'STAT_LOSSTRADES_AVGCON', 'STAT_COMPLEX_CRITERION',
  ]),
};

/** Names that are simply integers in MQL5 but read best as named constants. */
export const BUILTIN_CONSTANTS: [name: string, type: string, value: number | string][] = [
  ['WHOLE_ARRAY', 'int', -1],
  ['EMPTY', 'int', -1],
  ['INVALID_HANDLE', 'int', -1],
  ['WRONG_VALUE', 'int', -1],
  ['EMPTY_VALUE', 'double', Number.MAX_VALUE],
  ['DBL_MAX', 'double', Number.MAX_VALUE],
  ['DBL_MIN', 'double', 2.2250738585072014e-308],
  ['DBL_EPSILON', 'double', 2.220446049250313e-16],
  ['DBL_DIG', 'int', 15],
  ['DBL_MANT_DIG', 'int', 53],
  ['FLT_MAX', 'double', 3.402823466e38],
  ['FLT_MIN', 'double', 1.175494351e-38],
  ['FLT_EPSILON', 'double', 1.192092896e-7],
  ['FLT_DIG', 'int', 6],
  ['INT_MAX', 'int', 2147483647],
  ['INT_MIN', 'int', -2147483648],
  ['UINT_MAX', 'uint', 4294967295],
  ['LONG_MAX', 'long', Number.MAX_SAFE_INTEGER],
  ['LONG_MIN', 'long', Number.MIN_SAFE_INTEGER],
  ['ULONG_MAX', 'ulong', Number.MAX_SAFE_INTEGER],
  ['SHORT_MAX', 'short', 32767],
  ['SHORT_MIN', 'short', -32768],
  ['USHORT_MAX', 'ushort', 65535],
  ['CHAR_MAX', 'char', 127],
  ['CHAR_MIN', 'char', -128],
  ['UCHAR_MAX', 'uchar', 255],
  ['M_E', 'double', Math.E],
  ['M_LOG2E', 'double', Math.LOG2E],
  ['M_LOG10E', 'double', Math.LOG10E],
  ['M_LN2', 'double', Math.LN2],
  ['M_LN10', 'double', Math.LN10],
  ['M_PI', 'double', Math.PI],
  ['M_PI_2', 'double', Math.PI / 2],
  ['M_PI_4', 'double', Math.PI / 4],
  ['M_1_PI', 'double', 1 / Math.PI],
  ['M_2_PI', 'double', 2 / Math.PI],
  ['M_2_SQRTPI', 'double', 2 / Math.sqrt(Math.PI)],
  ['M_SQRT2', 'double', Math.SQRT2],
  ['M_SQRT1_2', 'double', Math.SQRT1_2],
  ['TIME_DATE', 'int', 1],
  ['TIME_MINUTES', 'int', 2],
  ['TIME_SECONDS', 'int', 4],
  ['CHARTS_MAX', 'int', 100],
  ['MAIN_LINE', 'int', 0],
  ['SIGNAL_LINE', 'int', 1],
  ['BASE_LINE', 'int', 0],
  ['UPPER_BAND', 'int', 1],
  ['LOWER_BAND', 'int', 2],
  ['PLUSDI_LINE', 'int', 1],
  ['MINUSDI_LINE', 'int', 2],
  ['UPPER_LINE', 'int', 0],
  ['LOWER_LINE', 'int', 1],
  ['TENKANSEN_LINE', 'int', 0],
  ['KIJUNSEN_LINE', 'int', 1],
  ['SENKOUSPANA_LINE', 'int', 2],
  ['SENKOUSPANB_LINE', 'int', 3],
  ['CHIKOUSPAN_LINE', 'int', 4],
  ['GATORJAW_LINE', 'int', 0],
  ['GATORTEETH_LINE', 'int', 1],
  ['GATORLIPS_LINE', 'int', 2],
  ['FILE_READ', 'int', 1],
  ['FILE_WRITE', 'int', 2],
  ['FILE_BIN', 'int', 4],
  ['FILE_CSV', 'int', 8],
  ['FILE_TXT', 'int', 16],
  ['FILE_ANSI', 'int', 32],
  ['FILE_UNICODE', 'int', 64],
  ['FILE_SHARE_READ', 'int', 128],
  ['FILE_SHARE_WRITE', 'int', 256],
  ['FILE_REWRITE', 'int', 512],
  ['FILE_COMMON', 'int', 4096],
  ['CP_ACP', 'int', 0],
  ['CP_OEMCP', 'int', 1],
  ['CP_UTF7', 'int', 65000],
  ['CP_UTF8', 'int', 65001],
  ['MB_OK', 'int', 0],
  ['MB_OKCANCEL', 'int', 1],
  ['MB_YESNO', 'int', 4],
  ['MB_ICONQUESTION', 'int', 32],
  ['MB_ICONWARNING', 'int', 48],
  ['MB_ICONINFORMATION', 'int', 64],
  ['MB_ICONERROR', 'int', 16],
  ['IDOK', 'int', 1],
  ['IDCANCEL', 'int', 2],
  ['IDYES', 'int', 6],
  ['IDNO', 'int', 7],
  ['SYMBOL_EXPIRATION_GTC', 'int', 1],
  ['SYMBOL_EXPIRATION_DAY', 'int', 2],
  ['SYMBOL_EXPIRATION_SPECIFIED', 'int', 4],
  ['SYMBOL_EXPIRATION_SPECIFIED_DAY', 'int', 8],
  ['SYMBOL_ORDER_MARKET', 'int', 1],
  ['SYMBOL_ORDER_LIMIT', 'int', 2],
  ['SYMBOL_ORDER_STOP', 'int', 4],
  ['SYMBOL_ORDER_STOP_LIMIT', 'int', 8],
  ['SYMBOL_ORDER_SL', 'int', 16],
  ['SYMBOL_ORDER_TP', 'int', 32],
  ['SYMBOL_ORDER_CLOSEBY', 'int', 64],
  ['CLR_NONE', 'color', -1],
  ['COPY_TICKS_ALL', 'int', -1],
  ['COPY_TICKS_INFO', 'int', 1],
  ['COPY_TICKS_TRADE', 'int', 2],
  ['TICK_FLAG_BID', 'int', 2],
  ['TICK_FLAG_ASK', 'int', 4],
  ['TICK_FLAG_LAST', 'int', 8],
  ['TICK_FLAG_VOLUME', 'int', 16],
  ['TICK_FLAG_BUY', 'int', 32],
  ['TICK_FLAG_SELL', 'int', 64],
  ['ERR_SUCCESS', 'int', 0],
  ['ERR_NO_ERROR', 'int', 0],
  ['ERR_INTERNAL_ERROR', 'int', 4001],
  ['ERR_WRONG_INTERNAL_PARAMETER', 'int', 4002],
  ['ERR_INVALID_PARAMETER', 'int', 4003],
  ['ERR_NOT_ENOUGH_MEMORY', 'int', 4004],
  ['ERR_STRUCT_WITHOBJECTS_ORCLASS', 'int', 4005],
  ['ERR_INVALID_ARRAY', 'int', 4006],
  ['ERR_ARRAY_RESIZE_ERROR', 'int', 4007],
  ['ERR_STRING_RESIZE_ERROR', 'int', 4008],
  ['ERR_NOTINITIALIZED_STRING', 'int', 4009],
  ['ERR_INVALID_DATETIME', 'int', 4010],
  ['ERR_ARRAY_BAD_SIZE', 'int', 4011],
  ['ERR_INVALID_POINTER', 'int', 4012],
  ['ERR_INVALID_POINTER_TYPE', 'int', 4013],
  ['ERR_FUNCTION_NOT_ALLOWED', 'int', 4014],
  ['ERR_CHART_WRONG_ID', 'int', 4101],
  ['ERR_OBJECT_ERROR', 'int', 4201],
  ['ERR_OBJECT_NOT_FOUND', 'int', 4202],
  ['ERR_MARKET_UNKNOWN_SYMBOL', 'int', 4301],
  ['ERR_MARKET_NOT_SELECTED', 'int', 4302],
  ['ERR_MARKET_WRONG_PROPERTY', 'int', 4303],
  ['ERR_MARKET_LASTTIME_UNKNOWN', 'int', 4304],
  ['ERR_HISTORY_NOT_FOUND', 'int', 4401],
  ['ERR_HISTORY_WRONG_PROPERTY', 'int', 4402],
  ['ERR_GLOBALVARIABLE_NOT_FOUND', 'int', 4501],
  ['ERR_ACCOUNT_WRONG_PROPERTY', 'int', 4701],
  ['ERR_TRADE_WRONG_PROPERTY', 'int', 4751],
  ['ERR_TRADE_DISABLED', 'int', 4752],
  ['ERR_TRADE_POSITION_NOT_FOUND', 'int', 4753],
  ['ERR_TRADE_ORDER_NOT_FOUND', 'int', 4754],
  ['ERR_TRADE_DEAL_NOT_FOUND', 'int', 4755],
  ['ERR_TRADE_SEND_FAILED', 'int', 4756],
  ['ERR_TRADE_CALC_FAILED', 'int', 4758],
  ['ERR_INDICATOR_UNKNOWN_SYMBOL', 'int', 4801],
  ['ERR_INDICATOR_CANNOT_CREATE', 'int', 4802],
  ['ERR_INDICATOR_WRONG_PARAMETERS', 'int', 4808],
  ['ERR_INDICATOR_DATA_NOT_FOUND', 'int', 4806],
  ['ERR_INDICATOR_WRONG_HANDLE', 'int', 4807],
  ['ERR_FILE_NOT_EXIST', 'int', 5019],
  ['ERR_FILE_CANNOT_OPEN', 'int', 5004],
  ['ERR_USER_ERROR_FIRST', 'int', 65536],
];

/**
 * MQL5's named colours — the web colour set, stored the MetaTrader way as
 * 0x00BBGGRR.
 */
const WEB_COLORS: [string, number][] = [
  ['Black', 0x000000], ['DarkGreen', 0x006400], ['DarkSlateGray', 0x2f4f4f], ['Olive', 0x808000], ['Green', 0x008000],
  ['Teal', 0x008080], ['Navy', 0x000080], ['Purple', 0x800080], ['Maroon', 0x800000], ['Indigo', 0x4b0082],
  ['MidnightBlue', 0x191970], ['DarkBlue', 0x00008b], ['DarkOliveGreen', 0x556b2f], ['SaddleBrown', 0x8b4513],
  ['ForestGreen', 0x228b22], ['OliveDrab', 0x6b8e23], ['SeaGreen', 0x2e8b57], ['DarkGoldenrod', 0xb8860b],
  ['DarkSlateBlue', 0x483d8b], ['Sienna', 0xa0522d], ['MediumBlue', 0x0000cd], ['Brown', 0xa52a2a],
  ['DarkTurquoise', 0x00ced1], ['DimGray', 0x696969], ['LightSeaGreen', 0x20b2aa], ['DarkViolet', 0x9400d3],
  ['FireBrick', 0xb22222], ['MediumVioletRed', 0xc71585], ['MediumSeaGreen', 0x3cb371], ['Chocolate', 0xd2691e],
  ['Crimson', 0xdc143c], ['SteelBlue', 0x4682b4], ['Goldenrod', 0xdaa520], ['MediumSpringGreen', 0x00fa9a],
  ['LawnGreen', 0x7cfc00], ['CadetBlue', 0x5f9ea0], ['DarkOrchid', 0x9932cc], ['YellowGreen', 0x9acd32],
  ['LimeGreen', 0x32cd32], ['OrangeRed', 0xff4500], ['DarkOrange', 0xff8c00], ['Orange', 0xffa500], ['Gold', 0xffd700],
  ['Yellow', 0xffff00], ['Chartreuse', 0x7fff00], ['Lime', 0x00ff00], ['SpringGreen', 0x00ff7f], ['Aqua', 0x00ffff],
  ['DeepSkyBlue', 0x00bfff], ['Blue', 0x0000ff], ['Magenta', 0xff00ff], ['Red', 0xff0000], ['Gray', 0x808080],
  ['SlateGray', 0x708090], ['Peru', 0xcd853f], ['BlueViolet', 0x8a2be2], ['LightSlateGray', 0x778899],
  ['DeepPink', 0xff1493], ['MediumTurquoise', 0x48d1cc], ['DodgerBlue', 0x1e90ff], ['Turquoise', 0x40e0d0],
  ['RoyalBlue', 0x4169e1], ['SlateBlue', 0x6a5acd], ['DarkKhaki', 0xbdb76b], ['IndianRed', 0xcd5c5c],
  ['MediumOrchid', 0xba55d3], ['GreenYellow', 0xadff2f], ['MediumAquamarine', 0x66cdaa], ['DarkSeaGreen', 0x8fbc8f],
  ['Tomato', 0xff6347], ['RosyBrown', 0xbc8f8f], ['Orchid', 0xda70d6], ['MediumPurple', 0x9370db],
  ['PaleVioletRed', 0xdb7093], ['Coral', 0xff7f50], ['CornflowerBlue', 0x6495ed], ['DarkGray', 0xa9a9a9],
  ['SandyBrown', 0xf4a460], ['MediumSlateBlue', 0x7b68ee], ['Tan', 0xd2b48c], ['DarkSalmon', 0xe9967a],
  ['BurlyWood', 0xdeb887], ['HotPink', 0xff69b4], ['Salmon', 0xfa8072], ['Violet', 0xee82ee], ['LightCoral', 0xf08080],
  ['SkyBlue', 0x87ceeb], ['LightSalmon', 0xffa07a], ['Plum', 0xdda0dd], ['Khaki', 0xf0e68c], ['LightGreen', 0x90ee90],
  ['Aquamarine', 0x7fffd4], ['Silver', 0xc0c0c0], ['LightSkyBlue', 0x87cefa], ['LightSteelBlue', 0xb0c4de],
  ['LightBlue', 0xadd8e6], ['PaleGreen', 0x98fb98], ['Thistle', 0xd8bfd8], ['PowderBlue', 0xb0e0e6],
  ['PaleGoldenrod', 0xeee8aa], ['PaleTurquoise', 0xafeeee], ['LightGray', 0xd3d3d3], ['Wheat', 0xf5deb3],
  ['NavajoWhite', 0xffdead], ['Moccasin', 0xffe4b5], ['LightPink', 0xffb6c1], ['Gainsboro', 0xdcdcdc],
  ['PeachPuff', 0xffdab9], ['Pink', 0xffc0cb], ['Bisque', 0xffe4c4], ['LightGoldenrod', 0xfafad2],
  ['BlanchedAlmond', 0xffebcd], ['LemonChiffon', 0xfffacd], ['Beige', 0xf5f5dc], ['AntiqueWhite', 0xfaebd7],
  ['PapayaWhip', 0xffefd5], ['Cornsilk', 0xfff8dc], ['LightYellow', 0xffffe0], ['LightCyan', 0xe0ffff],
  ['Linen', 0xfaf0e6], ['Lavender', 0xe6e6fa], ['MistyRose', 0xffe4e1], ['OldLace', 0xfdf5e6], ['WhiteSmoke', 0xf5f5f5],
  ['Seashell', 0xfff5ee], ['Ivory', 0xfffff0], ['Honeydew', 0xf0fff0], ['AliceBlue', 0xf0f8ff], ['LavenderBlush', 0xfff0f5],
  ['MintCream', 0xf5fffa], ['Snow', 0xfffafa], ['White', 0xffffff], ['Cyan', 0x00ffff], ['Fuchsia', 0xff00ff],
  ['LightGoldenrodYellow', 0xfafad2], ['DarkCyan', 0x008b8b], ['DarkMagenta', 0x8b008b], ['DarkRed', 0x8b0000],
  ['LightSlateBlue', 0x8470ff],
];

/** RGB 0xRRGGBB → MQL5 colour 0x00BBGGRR. */
export function rgbToMqlColor(rgb: number): number {
  const r = (rgb >> 16) & 0xff;
  const g = (rgb >> 8) & 0xff;
  const b = rgb & 0xff;
  return (b << 16) | (g << 8) | r;
}

export const COLOR_CONSTANTS: [name: string, value: number][] = [
  ['clrNONE', -1],
  ...WEB_COLORS.map(([name, rgb]): [string, number] => [`clr${name}`, rgbToMqlColor(rgb)]),
];

/** Every constant the compiler knows, with its type: enum members, plain constants and colours. */
export interface ConstantInfo {
  type: string;
  value: number | string;
  enumName?: string;
}

export function buildConstantTable(): Map<string, ConstantInfo> {
  const table = new Map<string, ConstantInfo>();
  for (const [enumName, members] of Object.entries(BUILTIN_ENUMS)) {
    for (const [name, value] of members) {
      if (!table.has(name)) table.set(name, { type: enumName, value, enumName });
    }
  }
  for (const [name, type, value] of BUILTIN_CONSTANTS) table.set(name, { type, value });
  for (const [name, value] of COLOR_CONSTANTS) table.set(name, { type: 'color', value });
  return table;
}

export const BUILTIN_TYPE_NAMES = new Set(Object.keys(BUILTIN_ENUMS));

/** Timeframe code → seconds per bar (months are handled by calendar, see series). */
export const TIMEFRAME_SECONDS: Record<number, number> = {
  1: 60, 2: 120, 3: 180, 4: 240, 5: 300, 6: 360, 10: 600, 12: 720, 15: 900, 20: 1200, 30: 1800,
  16385: 3600, 16386: 7200, 16387: 10800, 16388: 14400, 16390: 21600, 16392: 28800, 16396: 43200,
  16408: 86400, 32769: 604800, 49153: 2592000,
};

export function timeframeName(code: number): string {
  const entry = BUILTIN_ENUMS.ENUM_TIMEFRAMES!.find(([, value]) => value === code);
  return entry ? entry[0] : `PERIOD_${code}`;
}
