/**
 * Statistics for Deriv's digit contracts.
 *
 * Deriv's volatility indices are generated by a random number generator, not
 * by a market. Each tick's last digit is an independent draw from 0–9, and
 * Deriv publishes and audits that property. Nothing in a past sequence carries
 * information about the next draw.
 *
 * So this module measures and never forecasts. It reports what a window of
 * ticks actually contained, how far that sits from what chance alone produces,
 * and what each contract needs to be worth taking. A run of eight evens is a
 * fact about the past; it says nothing about the ninth, and the code below is
 * written so that no caller can mistake one for the other.
 */

export type DigitContract =
  | 'matches'
  | 'differs'
  | 'even'
  | 'odd'
  | 'over'
  | 'under';

export interface DigitCounts {
  /** How many times each digit 0–9 appeared, indexed by the digit. */
  readonly counts: readonly number[];
  readonly total: number;
}

export interface DigitStats extends DigitCounts {
  /** Observed share of each digit, 0–1. */
  readonly frequency: readonly number[];
  readonly even: number;
  readonly odd: number;
  /** The most and least seen digits in this window. Ties resolve to the lower digit. */
  readonly hottest: number;
  readonly coldest: number;
  /** How many of the most recent ticks shared the current parity. */
  readonly parityStreak: number;
  /** The digit of the most recent tick, or null when the window is empty. */
  readonly last: number | null;
}

/** The last decimal digit of a quote, as Deriv's digit contracts settle on. */
export function lastDigit(quote: number, decimals: number): number {
  if (!Number.isFinite(quote) || decimals < 0) return 0;
  // Rounded through a string: floating point turns 1234.56 * 100 into
  // 123455.99999 often enough to matter when the answer is a single digit.
  const fixed = quote.toFixed(decimals);
  const last = fixed[fixed.length - 1] ?? '0';
  const digit = Number(last);
  return Number.isFinite(digit) ? digit : 0;
}

/** Tallies a window of digits. The newest digit is expected last. */
export function tallyDigits(digits: readonly number[]): DigitStats {
  const counts = new Array<number>(10).fill(0);
  let even = 0;

  for (const digit of digits) {
    if (!Number.isInteger(digit) || digit < 0 || digit > 9) continue;
    counts[digit] = (counts[digit] ?? 0) + 1;
    if (digit % 2 === 0) even += 1;
  }

  const total = counts.reduce((sum, value) => sum + value, 0);
  const frequency = counts.map((value) => (total > 0 ? value / total : 0));

  let hottest = 0;
  let coldest = 0;
  for (let digit = 1; digit < 10; digit += 1) {
    if ((counts[digit] ?? 0) > (counts[hottest] ?? 0)) hottest = digit;
    if ((counts[digit] ?? 0) < (counts[coldest] ?? 0)) coldest = digit;
  }

  const last = digits.length > 0 ? (digits[digits.length - 1] ?? null) : null;
  let parityStreak = 0;
  if (last !== null) {
    const parity = last % 2;
    for (let i = digits.length - 1; i >= 0; i -= 1) {
      const digit = digits[i];
      if (digit === undefined || digit % 2 !== parity) break;
      parityStreak += 1;
    }
  }

  return { counts, total, frequency, even, odd: total - even, hottest, coldest, parityStreak, last };
}

/**
 * The chance a contract wins if the digits really are uniform.
 *
 * This is the number to compare a payout against. It is fixed by the rules of
 * the contract, not estimated from the window, because the window cannot
 * improve on a known distribution.
 */
export function fairWinChance(contract: DigitContract, barrier: number): number {
  switch (contract) {
    case 'matches':
      return 0.1;
    case 'differs':
      return 0.9;
    case 'even':
    case 'odd':
      return 0.5;
    // Over N wins on N+1..9; Under N wins on 0..N-1.
    case 'over':
      return Math.min(1, Math.max(0, (9 - barrier) / 10));
    case 'under':
      return Math.min(1, Math.max(0, barrier / 10));
  }
}

/**
 * Expected return per unit staked, given a payout multiple.
 *
 * `payoutMultiple` is what one unit of stake returns in total when the
 * contract wins — so 1.95 means a 0.95 profit. A negative result is the
 * house's margin, and for these contracts it is negative by construction.
 */
export function expectedValue(
  contract: DigitContract,
  barrier: number,
  payoutMultiple: number,
): number {
  const p = fairWinChance(contract, barrier);
  return p * payoutMultiple - 1;
}

/** The payout multiple at which a contract would break even. */
export function breakEvenPayout(contract: DigitContract, barrier: number): number {
  const p = fairWinChance(contract, barrier);
  return p > 0 ? 1 / p : Number.POSITIVE_INFINITY;
}

/**
 * How unusual an observed count is, as a standard-normal z-score.
 *
 * Given for honesty rather than for signal: it answers "is this window odd?",
 * and for a uniform generator the answer wanders across ±2 all day long
 * without any of it meaning the next digit is predictable.
 */
export function zScore(observed: number, total: number, probability: number): number {
  if (total <= 0) return 0;
  const mean = total * probability;
  const variance = total * probability * (1 - probability);
  if (variance <= 0) return 0;
  return (observed - mean) / Math.sqrt(variance);
}

/**
 * Whether a window's digit spread departs from uniform by more than sampling
 * noise comfortably explains.
 *
 * A chi-squared statistic over nine degrees of freedom; 16.92 is the 95th
 * percentile and 21.67 the 99th. Even a clear result here is evidence about
 * the generator, never about the next tick.
 */
export function uniformityChiSquared(stats: DigitCounts): number {
  if (stats.total <= 0) return 0;
  const expected = stats.total / 10;
  let total = 0;
  for (let digit = 0; digit < 10; digit += 1) {
    const diff = (stats.counts[digit] ?? 0) - expected;
    total += (diff * diff) / expected;
  }
  return total;
}

export type Uniformity = 'consistent' | 'unusual' | 'very-unusual' | 'insufficient';

/** Reads the chi-squared against its critical values, with a floor on sample size. */
export function readUniformity(stats: DigitCounts): Uniformity {
  // Below roughly five expected per cell the statistic is not trustworthy.
  if (stats.total < 50) return 'insufficient';
  const chi = uniformityChiSquared(stats);
  if (chi > 21.67) return 'very-unusual';
  if (chi > 16.92) return 'unusual';
  return 'consistent';
}
